import { randomUUID } from "node:crypto";
import type { ToolClientResult } from "@/lib/agent/events";

// ─────────────────────────────────────────────────────────────────────────────
// In-memory agent session registry — the bridge that lets a parked agent-loop
// await results posted from the browser on a SEPARATE request
// (POST /api/agent/respond) while the original NDJSON stream stays open.
//
// globalThis-persisted so Turbopack hot reloads don't orphan live sessions.
// One session = one browser tab's agent channel (sessionId is generated by the
// client and reused across runs; pending calls are per-run).
// ─────────────────────────────────────────────────────────────────────────────

export interface PendingCall {
  callId: string;
  resolve: (result: ToolClientResult) => void;
  reject: (err: Error) => void;
  /** Pending confirmation also rides this channel — approved flag result. */
  kind: "tool" | "confirmation";
  timer: ReturnType<typeof setTimeout>;
  createdAt: number;
}

export interface AgentSession {
  sessionId: string;
  /** The run currently owning the channel (one at a time per session). */
  runId: string | null;
  abort: AbortController;
  pending: Map<string, PendingCall>;
  /** callId → action-log row id, so tool_status POSTs can patch the row while
   * the tool call is still parked (transaction lifecycle, §4.6). */
  callActions: Map<string, { runId: string; actionId: string; tool: string }>;
  lastSeen: number;
}

const G = globalThis as unknown as {
  __acpAgentSessions?: Map<string, AgentSession>;
};

function sessions(): Map<string, AgentSession> {
  if (!G.__acpAgentSessions) G.__acpAgentSessions = new Map();
  return G.__acpAgentSessions;
}

export function getOrCreateSession(sessionId: string): AgentSession {
  const map = sessions();
  let s = map.get(sessionId);
  if (!s) {
    s = { sessionId, runId: null, abort: new AbortController(), pending: new Map(), callActions: new Map(), lastSeen: Date.now() };
    map.set(sessionId, s);
  } else {
    s.lastSeen = Date.now();
  }
  // Reuse the session but a fresh AbortController per run is managed by the loop.
  return s;
}

export function getSession(sessionId: string): AgentSession | undefined {
  return sessions().get(sessionId);
}

/** Called by the run loop when it starts owning the channel. */
export function bindRun(sessionId: string, runId: string): void {
  const s = getOrCreateSession(sessionId);
  s.runId = runId;
  // Abandon any leftover pending calls from a previous crashed run.
  for (const [id, p] of s.pending) {
    clearTimeout(p.timer);
    p.reject(new Error("run superseded"));
    s.pending.delete(id);
  }
}

/** Register a parked wait. Resolves when the client POSTs a respond, or on timeout/abort. */
export function awaitResponse<T extends "tool" | "confirmation">(
  sessionId: string,
  callId: string,
  kind: T,
  timeoutMs: number,
  signal?: AbortSignal,
): Promise<T extends "tool" ? ToolClientResult : { approved: boolean; rememberChoice?: boolean }> {
  const s = getOrCreateSession(sessionId);
  return new Promise((resolve, reject) => {
    // An ALREADY-aborted signal must reject immediately — addEventListener on
    // an aborted AbortSignal never fires, so a late registration would park
    // the run for the full timeout instead of interrupting.
    if (signal?.aborted) {
      reject(new DOMException("aborted", "AbortError"));
      return;
    }
    const cleanup = () => {
      const p = s.pending.get(callId);
      if (p) {
        clearTimeout(p.timer);
        s.pending.delete(callId);
      }
      signal?.removeEventListener("abort", onAbort);
    };
    const onAbort = () => {
      cleanup();
      reject(new DOMException("aborted", "AbortError"));
    };
    const timer = setTimeout(() => {
      cleanup();
      reject(new Error(`timeout waiting for ${kind} response (callId ${callId})`));
    }, timeoutMs);
    const entry: PendingCall = {
      callId,
      kind,
      timer,
      createdAt: Date.now(),
      resolve: (result) => {
        cleanup();
        resolve(result as T extends "tool" ? ToolClientResult : { approved: boolean; rememberChoice?: boolean });
      },
      reject: (err) => {
        cleanup();
        reject(err);
      },
    };
    s.pending.set(callId, entry);
    signal?.addEventListener("abort", onAbort, { once: true });
  }) as Promise<T extends "tool" ? ToolClientResult : { approved: boolean; rememberChoice?: boolean }>;
}

/** POST /api/agent/respond handler resolves a parked wait. */
export function resolveResponse(sessionId: string, callId: string, payload: ToolClientResult | { approved: boolean; rememberChoice?: boolean }): boolean {
  const s = sessions().get(sessionId);
  if (!s) return false;
  const p = s.pending.get(callId);
  if (!p) return false;
  p.resolve(payload as ToolClientResult);
  return true;
}

/** The loop binds callId → action row so mid-flight lifecycle POSTs
 * (tool_status) can patch the persistent action log in real time. */
export function bindCallAction(sessionId: string, callId: string, runId: string, actionId: string, tool: string): void {
  const s = getOrCreateSession(sessionId);
  s.callActions.set(callId, { runId, actionId, tool });
}

/** Look up the bound action row for a tool_status POST. */
export function getCallAction(sessionId: string, callId: string): { runId: string; actionId: string; tool: string } | undefined {
  return sessions().get(sessionId)?.callActions.get(callId);
}

/** Housekeeping: drop sessions idle > 30 min with no pending calls. */
export function sweepSessions(): void {
  const map = sessions();
  const cutoff = Date.now() - 30 * 60_000;
  for (const [id, s] of map) {
    if (s.pending.size === 0 && s.lastSeen < cutoff) map.delete(id);
  }
}

export function newRunId(): string {
  return `run_${Date.now().toString(36)}_${randomUUID().slice(0, 8)}`;
}
